### ISSUE TITLE
trackIDOrStream

### ISSUE THREAD

**Issue by galbarm** [rayryeng/RTSPTest#1]
Hi, nice job with this RTSP client implementation. Saved me a lot of work.
It worked out of the box with an IP camera, except for one thing:

The track id on that RTSP server was not represented as "TrackId=" nor "stream", but "track".

**Comment by rayryeng** [comment]
@galbarm  - Hi!  Thanks for the feedback!  I'm assuming your changes got it to work with your IP camera. If you could submit a pull request regarding your changes, I'd love to integrate this into the test code.

Thanks!

**Comment by rayryeng** [comment]
@galbarm ... or if you don't want, let me commit some changes, you try them out and let me know if they work.  The RTSP servers that I'm used to working with have "trackID" as the delimiter instead of just "track".  If it works just by using "track", then I just have to change a couple lines of code.  Let me know.

**Comment by galbarm** [comment]
@rayryeng Yes, that's all you need to change. I've made some changes to make it work for me in the specific case but the code is not general enough to commit it.

**Comment by rayryeng** [comment]
@galbarm  - OK.  Should I close this issue then?

**Comment by galbarm** [comment]
@rayryeng It's totally up to you. I've fixed it locally for myself.
If you fix it you should close it, otherwise you should leave it opened.

**Comment by rayryeng** [comment]
@galbarm  - I've committed some changes.  Very minor.  I have another case that just looks for "track" on top of "trackID" and "stream".  Now closing this issue.  Thanks!
