### ISSUE TITLE
SETUP Uri from Session Description is incorrect

### ISSUE THREAD

**Issue by juliusfriedman** [rayryeng/RTSPTest#4]
To whom it may concern,

For some reason this library adds an unwanted string to SETUP requests, an example of the added string would be "track=" or "trackID=".

I am not sure why you choose to hard code these tokens especially since you go through the trouble to parse them, the tokens can be literally anything allowed in the grammar such as but not limited to "audio", "video", "text", "track", "stream", "XYZ"....

See Wikipedia for an example that doesn't use track or trackId...

https://en.wikipedia.org/wiki/Real_Time_Streaming_Protocol

Or the RFC for many more

https://www.ietf.org/rfc/rfc2326.txt

Please also this this IETF mailing list entry which specifically clarifies this for someone else...

https://www.ietf.org/mail-archive/web/mmusic/current/msg00880.html

In short, the 'control' line of the Media Description of the Session Description is used to specify aggregate control of a media item. (This means that each stream can be controlled independently of the other)

If that media item does not specify a control line or specifies "*" then the Session Description Control Line is used.

If the control line specifies a relative format it is usually accompanied by a 'Content-Base' header in the RTSP Response which specifies the absolute portion of the relative URI in the control line.

This means that literally anything can appear in the control line, even another servers address.

This needs to be handled especially because the resource may not reside within the same domain as the rtsp server itself, thus the request needs to be sent to the server indicated in the control line.

You can see how I handled this in my RtspClient by obtaining the Content-Base header when required
http://net7mma.codeplex.com/SourceControl/latest#Rtsp/RtspClient.cs

You can see how I retrieve the AggregateControl Uri from the MediaDescription or SessionDescription 
http://net7mma.codeplex.com/SourceControl/latest#Sdp/MediaDescription.cs

This prevents your client form working with my RtspServer as well as various other servers which do not use the 'track' or 'trackId' string but something else.

Since this project is advertised as standards compliant I figured I should let you know.

Regards,

**Comment by rayryeng** [comment]
I'll modify the README.  This worked for me for MPEG specific data only.  It doesn't work for anything else.  Closing your issue.
